warning:
  - 'Nem lehet a végtelenségig húzni...'
  - 'Igen, igen, van még idő, de azért már nem sok.'
  - 'Csinálom itt a fesztivált, megvárom míg piros lesz.'
  - 'A warningokat a kódban is mindig figyelmen kívül hagyom...'
  - 'Ha most megcsinálnám, akkor nem lenne végtelen beadandóm jövőhéten.'
  - 'Sokallom.'
  - 'Volt már olyan, amit meg tudtam csinálni egy nap alatt?'
  - 'Holnap elkezdem. Vagy holnapután. Áááh...'
  - 'Több, mint egy hét elég behozni a lemaradásom minden másból.'
  - 'Vajon ad ötöst Tanár Úr, ha nem várom meg, hogy piros legyen?'
  - 'Nem várt szabadidő a héten.'
danger:
  - 'Már nincs egy hét rá, jáááj!'
  - 'Hét, azaz 7 nap. Na, annyi nincs.'
  - 'FFFFFFFUUUUUUUU'
  - 'Vajon feltölthetem még határidő után is? (NEM - a szerk.)'
  - 'De miért, miért most, amikor egy hónapja még emlékeztem is rá?'
  - 'Jó lenne tudni legalább, hogy mit kell megcsinálnom a héten...'
  - 'Ccajj, moziba akartam menni este.'
  - 'Olyan fícsör nem lesz, hogy ki csinálta már meg?'
  - 'Minek aggódni? Eddig is mindent határidő előtt egy perccel küldtem.'
